# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/doxygen
image: debian

pages:
  stage: deploy
  script:
  - apt-get update -y && apt-get install -y ant openjdk-8-jdk
  - ant
  - mkdir -p ./public/lib
  - cp dist/lib/*.jar ./public/lib
  - mkdir -p ./public/javadoc
  - cd javadoc/doc
  - cp -r * ../../public/javadoc
  artifacts:
    paths:
    - public
    - dist
  only:
  - master
